services:
  # PostgreSQL container
  db:
    image: postgres:17.2
      # ports:
      #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Volume for development
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    mem_limit: 500m
    networks:
      - backend

  # GoodJob container
  goodjob:
    build:
      context: .
      args:
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
        # - SENDGRID_API_KEY=${SENDGRID_API_KEY} # Add this line
    command: bundle exec rails good_job start
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
    networks:
      - backend
    mem_limit: 500m

  # Webserver container
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    env_file:
      - ".env"
    ports:
      - "3001:3000"
    depends_on:
      - db
      - goodjob
    environment:
      - GUI_AVAILABLE=false
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
        # - SENDGRID_API_KEY=${SENDGRID_API_KEY} # Add this line
    mem_limit: 1g
    stdin_open: true
    tty: true
    networks:
      - backend

volumes:
  pgdata: {}

networks:
  backend:
    driver: bridge

